require("dotenv").config();


module.exports = {
    MESSAGE_BROKER_URL: process.env.MESSAGE_BROKER_URL,
    EXCHANGE_NAME: 'LUXEHUB',
    ORDER_BINDING_KEY: 'ORDER_SERVICE',
    PAYMENT_BINDING_KEY: 'PAYMENT_SERVICE',
    CART_BINDING_KEY: 'CART_SERVICE',
    PAYMENT_QUEUE: 'PAYMENT_QUEUE'// FROM: which microservice
}